services:
  - type: worker
    name: kino-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: DB_PATH
        value: /var/data/kinobot.db
